{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "artificial-memory-operator.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "artificial-memory-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "artificial-memory-operator.name" . }}
      app.kubernetes.io/component: operator
  endpoints:
    - port: http
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
---
{{- end }}