"""Background reflection (AM v0.2.0 Phase 5).

Plan #13 / #14: memory management happens *outside* the critical response
path. On a trigger (idle time, end of session, low load, memory pressure,
contradiction detection, scheduled maintenance, unresolved clusters) the
reflector selects a bounded set of **reflection candidates**, reviews them,
and — crucially — does **not** mutate anything itself::

    Candidate Selection
        ↓ Evidence Retrieval
        ↓ Memory Review / State Assessment
        ↓ Proposed Mutation (EvolutionProposal)
        ↓ Policy Validation (EvolutionGovernor)
        ↓ Commit
        ↓ Audit Event

The reflection model is a *proposer*, never a database writer (plan #26).

Phase 5 status: proposals are generated by deterministic heuristics over the
Phase 1 state vector, access statistics and association evidence. An LLM
reviewer can later replace the heuristic step — it would submit through the
same ``EvolutionProposal`` interface and face the same ``EvolutionGovernor``
validation, which is exactly why the gate was built first (Q7).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from typing import Any

from artificial_memory.core.interfaces import MemoryStore
from artificial_memory.core.models import Memory
from artificial_memory.memory.evolution import EvolutionOperationType
from artificial_memory.memory.evolution_policy import (
    EvolutionGovernor,
    EvolutionProposal,
    PolicyDecision,
)
from artificial_memory.memory.state_signals import (
    MemoryStateVector,
    StateSignalCalculator,
)


class ReflectionTrigger(StrEnum):
    """What woke the reflector up (plan #13 trigger list)."""

    IDLE = "idle"
    SESSION_END = "session_end"
    LOW_LOAD = "low_load"
    MEMORY_PRESSURE = "memory_pressure"
    CONTRADICTION_DETECTED = "contradiction_detected"
    SCHEDULED = "scheduled"
    UNRESOLVED_CLUSTERS = "unresolved_clusters"


class ReflectionKind(StrEnum):
    """The review verdict for one candidate (plan Phase 5 list)."""

    REINFORCE = "reinforce"
    MERGE = "merge"
    REINTERPRET = "reinterpret"
    ARCHIVE = "archive"
    KEEP = "keep"


@dataclass
class ReflectionConfig:
    """Deterministic thresholds for candidate review."""

    # Bounded review: never inspect the whole store indiscriminately.
    max_candidates: int = 25
    max_proposals: int = 10
    # Produce findings without submitting them (plan #14 rehearsal mode).
    dry_run: bool = False

    # REINFORCE: frequently accessed, valuable memories get strengthened.
    reinforce_min_access_count: int = 3
    reinforce_min_importance: float = 0.6
    # KEEP: rarely accessed but valuable memories get an explicit retention
    # decision before age-based processes can touch them.
    keep_min_importance: float = 0.7
    keep_max_access_count: int = 1
    keep_min_age_days: float = 14.0
    # ARCHIVE: low future utility, old, low confidence -> archived (never
    # deleted; "forgetting = resolution down", plan #4).
    archive_max_future_utility: float = 0.30
    archive_min_age_days: float = 30.0
    archive_max_confidence: float = 0.6
    # MERGE: duplicate clusters via lexical overlap between candidates.
    merge_min_overlap: float = 0.75
    # REINTERPRET: unstable interpretation with enough related evidence.
    reinterpret_min_related: int = 2

    def __post_init__(self) -> None:
        if self.max_candidates <= 0 or self.max_proposals <= 0:
            raise ValueError("max_candidates and max_proposals must be positive")
        if not 0.0 <= self.merge_min_overlap <= 1.0:
            raise ValueError("merge_min_overlap must be within [0, 1]")
        if not 0.0 <= self.archive_max_future_utility <= 1.0:
            raise ValueError("archive_max_future_utility must be within [0, 1]")

@dataclass
class ReflectionFinding:
    """One candidate's review outcome with the mutation it would propose."""

    memory: Memory
    kind: ReflectionKind
    rationale: str
    proposal: EvolutionProposal
    signals: dict[str, float] = field(default_factory=dict)
    evidence_ids: list[int] = field(default_factory=list)
    memory_id: int = 0

    def __post_init__(self) -> None:
        self.memory_id = self.memory.id or 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "memory_id": self.memory_id,
            "kind": self.kind.value,
            "rationale": self.rationale,
            "evidence_ids": list(self.evidence_ids),
            "proposal": {
                "operation": self.proposal.operation.value,
                "confidence": self.proposal.confidence,
                "reason": self.proposal.reason,
                "evidence": self.proposal.evidence,
            },
        }


@dataclass
class ReflectionReport:
    """The full record of one reflection run (auditable, serializable)."""

    trigger: ReflectionTrigger
    started_at: datetime
    finished_at: datetime | None = None
    reviewed: int = 0
    findings: list[ReflectionFinding] = field(default_factory=list)
    decisions: list[PolicyDecision] = field(default_factory=list)
    dry_run: bool = False

    @property
    def proposals(self) -> list[EvolutionProposal]:
        return [finding.proposal for finding in self.findings]

    @property
    def approved(self) -> int:
        return sum(1 for decision in self.decisions if decision.approved)

    @property
    def rejected(self) -> int:
        return sum(1 for decision in self.decisions if not decision.approved)

    def to_dict(self) -> dict[str, Any]:
        return {
            "trigger": self.trigger.value,
            "started_at": self.started_at.isoformat(),
            "finished_at": self.finished_at.isoformat() if self.finished_at else None,
            "reviewed": self.reviewed,
            "dry_run": self.dry_run,
            "findings": [finding.to_dict() for finding in self.findings],
            "decisions": [
                {
                    "operation": decision.proposal.operation.value,
                    "memory_id": decision.proposal.memory_id,
                    "verdict": decision.verdict.value,
                    "reasons": list(decision.reasons),
                    "committed": decision.committed,
                    "resulting_memory_id": decision.resulting_memory_id,
                }
                for decision in self.decisions
            ],
            "approved": self.approved,
            "rejected": self.rejected,
        }

class BackgroundReflector:
    """Runs the plan #14 reflection pipeline over a bounded candidate set."""

    def __init__(
        self,
        store: MemoryStore,
        governor: EvolutionGovernor | None = None,
        config: ReflectionConfig | None = None,
        calculator: StateSignalCalculator | None = None,
    ):
        self.store = store
        if governor is None:
            from artificial_memory.compression.compressor import RuleBasedCompressor
            from artificial_memory.memory.evolution import MemoryEvolutionEngine

            governor = EvolutionGovernor(
                MemoryEvolutionEngine(store, RuleBasedCompressor())
            )
        self.governor = governor
        self.config = config or ReflectionConfig()
        self.calculator = calculator or StateSignalCalculator(store)

    # ==================== Public API ====================

    def run(
        self,
        trigger: ReflectionTrigger = ReflectionTrigger.IDLE,
        now: datetime | None = None,
    ) -> ReflectionReport:
        """Execute one reflection pass: review, propose, validate, commit."""
        now = now or datetime.now()
        report = ReflectionReport(trigger=trigger, started_at=now, dry_run=self.config.dry_run)

        candidates = self._select_candidates(now)
        report.reviewed = len(candidates)
        if not candidates:
            report.finished_at = datetime.now()
            return report

        for memory in candidates:
            state = self.calculator.compute_state_vector(memory, now=now)
            finding = self._review(memory, state, candidates, now)
            if finding is None:
                continue
            report.findings.append(finding)

        for finding in report.findings[: self.config.max_proposals]:
            if self.config.dry_run:
                continue
            decision = self.governor.submit(finding.proposal)
            report.decisions.append(decision)

        report.finished_at = datetime.now()
        return report

    # ==================== Candidate selection (plan #13) ====================

    def _select_candidates(self, now: datetime) -> list[Memory]:
        """Pick the memories worth reviewing this pass.

        Reflection priority rises with usage and importance and with decay of
        currency and utility — the plan's "frequently accessed" and
        "approaching archival thresholds" families — so the review budget is
        spent where memory management matters most.
        """
        memories = self.store.get_memories(is_current=True, limit=200)
        scored: list[tuple[float, int, Memory, MemoryStateVector]] = []
        for memory in memories:
            if memory.status.value not in ("active", "dormant"):
                continue
            state = self.calculator.compute_state_vector(memory, now=now)
            usage = state.signals.get("usage", 0.0)
            priority = (
                0.30 * usage
                + 0.25 * memory.importance
                + 0.25 * (1.0 - state.currentness)
                + 0.20 * (1.0 - state.future_utility)
            )
            memory_id = memory.id or 0
            scored.append((priority, memory_id, memory, state))
        scored.sort(key=lambda entry: (-entry[0], entry[1]))
        return [entry[2] for entry in scored[: self.config.max_candidates]]

    # ==================== Merge detection ====================

    def _find_duplicate(
        self,
        memory: Memory,
        candidates: list[Memory],
        consumed: set[int],
    ) -> Memory | None:
        """The first candidate with lexical overlap above the threshold."""
        from artificial_memory.memory.evidence import tokenize  # local: cycle guard

        target_tokens = tokenize(memory.content)
        if not target_tokens:
            return None
        for other in candidates:
            if other.id is None or other.id == memory.id or other.id in consumed:
                continue
            other_tokens = tokenize(other.content)
            if not other_tokens:
                continue
            shared = target_tokens & other_tokens
            smaller = min(len(target_tokens), len(other_tokens))
            overlap = len(shared) / smaller if smaller else 0.0
            if overlap >= self.config.merge_min_overlap:
                return other
        return None

    # ==================== Review (plan #14) ====================

    def _review(
        self,
        memory: Memory,
        state: MemoryStateVector,
        candidates: list[Memory],
        now: datetime,
    ) -> ReflectionFinding | None:
        """Assess one candidate and produce at most one proposed mutation.

        Review order matters: destructive operations (merge / archive) are
        considered before non-destructive ones (reinforce / keep /
        reinterpret), and each memory yields at most one proposal per pass.
        """
        memory_id = memory.id or 0
        age_days = self._age_days(memory, now)
        usage = state.signals.get("usage", 0.0)

        # --- MERGE: duplicate cluster ---
        duplicate = self._find_duplicate(memory, candidates, consumed=set())
        if duplicate is not None:
            overlap = self._overlap_ratio(memory, duplicate)
            return self._finding(
                memory,
                ReflectionKind.MERGE,
                rationale=(
                    f"Duplicate cluster: {overlap:.0%} lexical overlap with "
                    f"memory {duplicate.id}."
                ),
                proposal=EvolutionProposal(
                    operation=EvolutionOperationType.MERGE,
                    memory_id=memory_id,
                    reason=(
                        f"Merging duplicate of memory {duplicate.id} "
                        f"(overlap {overlap:.2f}) detected during reflection."
                    ),
                    confidence=min(0.95, 0.6 + 0.35 * overlap),
                    merge_memory_ids=[duplicate.id or 0],
                    metadata={"triggered_by": "reflection"},
                ),
                state=state,
                evidence_ids=[duplicate.id or 0],
            )

        # --- ARCHIVE: approaching the archival threshold ---
        if (
            state.future_utility <= self.config.archive_max_future_utility
            and age_days >= self.config.archive_min_age_days
            and state.confidence <= self.config.archive_max_confidence
        ):
            return self._finding(
                memory,
                ReflectionKind.ARCHIVE,
                rationale=(
                    f"future_utility={state.future_utility:.2f}, confidence="
                    f"{state.confidence:.2f}, age {age_days:.0f}d: below "
                    "archival thresholds."
                ),
                proposal=EvolutionProposal(
                    operation=EvolutionOperationType.TRANSITION,
                    memory_id=memory_id,
                    reason=(
                        "Archival reflection: low utility, low confidence and "
                        "stale; archived rather than deleted (plan #4)."
                    ),
                    confidence=min(0.95, 0.6 + 0.3 * (1.0 - state.future_utility)),
                    metadata={
                        "triggered_by": "reflection",
                        "to_status": "archived",
                    },
                ),
                state=state,
            )

        # --- REINFORCE: frequently accessed, valuable ---
        if (
            memory.access_count >= self.config.reinforce_min_access_count
            and memory.importance >= self.config.reinforce_min_importance
        ):
            return self._finding(
                memory,
                ReflectionKind.REINFORCE,
                rationale=(
                    f"Frequently accessed ({memory.access_count}x) with "
                    f"importance {memory.importance:.2f}."
                ),
                proposal=EvolutionProposal(
                    operation=EvolutionOperationType.REINFORCE,
                    memory_id=memory_id,
                    reason=(
                        "Reinforcement reflection: repeated usage confirms "
                        "this memory stays load-bearing."
                    ),
                    evidence=f"access_count={memory.access_count}, usage={usage:.2f}",
                    confidence=min(0.95, 0.5 + 0.4 * usage),
                    metadata={"triggered_by": "reflection"},
                ),
                state=state,
            )

        # --- KEEP: rarely accessed high-value memory ---
        if (
            memory.importance >= self.config.keep_min_importance
            and memory.access_count <= self.config.keep_max_access_count
            and age_days >= self.config.keep_min_age_days
        ):
            return self._finding(
                memory,
                ReflectionKind.KEEP,
                rationale=(
                    f"Valuable (importance {memory.importance:.2f}) but rarely "
                    f"accessed ({memory.access_count}x) for {age_days:.0f}d."
                ),
                proposal=EvolutionProposal(
                    operation=EvolutionOperationType.KEEP,
                    memory_id=memory_id,
                    reason=(
                        "Retention reflection: explicit KEEP so age-based "
                        "processes do not silently erode a valuable memory."
                    ),
                    confidence=min(0.9, 0.5 + 0.3 * memory.importance),
                    metadata={"triggered_by": "reflection"},
                ),
                state=state,
            )

        # --- REINTERPRET: unstable interpretation with related evidence ---
        related = self.store.get_related_memories(memory_id, min_strength=0.4)
        if len(related) >= self.config.reinterpret_min_related:
            interpretation = self._interpretation(memory, related)
            return self._finding(
                memory,
                ReflectionKind.REINTERPRET,
                rationale=(
                    f"{len(related)} related memories allow a broader, more "
                    "stable interpretation."
                ),
                proposal=EvolutionProposal(
                    operation=EvolutionOperationType.REINTERPRET,
                    memory_id=memory_id,
                    reason=(
                        "Reinterpretation reflection: related evidence "
                        "indicates a stable higher-order pattern."
                    ),
                    evidence=", ".join(str(other.id or 0) for other, _ in related[:5]),
                    interpretation=interpretation,
                    confidence=min(0.9, 0.6 + 0.2 * min(len(related) / 5.0, 1.0)),
                    metadata={"triggered_by": "reflection", "supersede": False},
                ),
                state=state,
                evidence_ids=[other.id or 0 for other, _ in related[:5]],
            )

        return None

    # ==================== Helpers ====================

    @staticmethod
    def _age_days(memory: Memory, now: datetime) -> float:
        reference = memory.last_accessed or memory.created_at
        return max(0.0, (now - reference).total_seconds() / 86400.0)

    @staticmethod
    def _overlap_ratio(memory: Memory, other: Memory) -> float:
        from artificial_memory.memory.evidence import tokenize  # local: cycle guard

        a = tokenize(memory.content)
        b = tokenize(other.content)
        if not a or not b:
            return 0.0
        smaller = min(len(a), len(b))
        return len(a & b) / smaller if smaller else 0.0

    def _interpretation(self, memory: Memory, related: list[tuple[Memory, Any]]) -> str:
        """Deterministic interpretation text synthesized from related evidence."""
        from artificial_memory.memory.evidence import tokenize  # local: cycle guard

        counts: dict[str, int] = {}
        for other, _association in related:
            for token in tokenize(other.content):
                counts[token] = counts.get(token, 0) + 1
        shared = [token for token, count in counts.items() if count >= 2]
        shared.sort(key=lambda token: (-counts[token], token))
        keywords = ", ".join(shared[:4]) or "the recorded evidence"
        return (
            f"Stable pattern across {len(related)} related memories, "
            f"recurring around: {keywords}."
        )

    def _finding(
        self,
        memory: Memory,
        kind: ReflectionKind,
        rationale: str,
        proposal: EvolutionProposal,
        state: MemoryStateVector,
        evidence_ids: list[int] | None = None,
    ) -> ReflectionFinding:
        return ReflectionFinding(
            memory=memory,
            kind=kind,
            rationale=rationale,
            proposal=proposal,
            signals=dict(state.signals),
            evidence_ids=evidence_ids or [],
        )


def create_background_reflector(
    store: MemoryStore,
    config: ReflectionConfig | None = None,
    governor: EvolutionGovernor | None = None,
) -> BackgroundReflector:
    return BackgroundReflector(store, governor, config)


__all__ = [
    "BackgroundReflector",
    "ReflectionConfig",
    "ReflectionFinding",
    "ReflectionKind",
    "ReflectionReport",
    "ReflectionTrigger",
    "create_background_reflector",
]




